source 'https://rubygems.org'
ruby '2.1.0'

gem 'rails', '4.0.2'

gem 'activevalidators'
gem 'bootstrap-sass'
gem 'cancan'
gem 'carrierwave'
gem 'coffee-rails'
gem 'devise'
gem 'fog'
gem 'font-awesome-rails'
gem 'haml-rails'
gem 'inherited_resources'
gem 'jbuilder'
gem 'jquery-rails'
gem 'mini_magick'
gem 'newrelic_rpm'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'pg'
gem 'phony_rails'
gem 'rails-i18n'
gem 'rails_admin'
gem 'rollbar'
gem 'sass-rails'
gem 'simple_form'
gem 'simple_navigation_renderers'
gem 'therubyracer'
gem 'turbolinks'
gem 'uglifier'
gem 'unf'
gem 'unicorn'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capybara'
  gem 'capybara-email'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'foreman'
  gem 'forgery'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'spring'
  gem 'spring-commands-rspec'
end

group :doc do
  gem 'sdoc', require: false
end

group :production do
  gem 'rails_12factor'
end
