source 'https://rubygems.org'
ruby '2.3.7'

gem 'rails', '~>5.0'

gem 'activevalidators'
gem 'bootstrap-sass'
gem 'cancancan'
gem 'carrierwave'
gem 'coffee-rails'
gem 'devise'
gem 'fog'
gem 'font-awesome-rails'
gem 'haml-rails'
gem 'has_scope'
gem 'inherited_resources', '>=1.4.1'
gem 'jbuilder'
gem 'jquery-rails'
gem 'markerb'
gem 'redcarpet'
gem 'mini_magick'
gem 'pg'
gem 'phony_rails'
gem 'rails-i18n'
gem 'rails_admin'
gem 'sass-rails', '>=4.0.2'
gem 'simple_form'
gem 'simple_navigation_renderers'
gem 'social-share-button'
gem 'therubyracer'
gem 'uglifier'
gem 'unf'
gem 'validate_url'
gem 'email_validator'
gem 'kaminari'
gem 'rest-client'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'rqrcode'
gem 'storext'
gem 'rich', github: 'kreativgebiet/rich'
gem 'paperclip'
gem 'aws-sdk'
gem 'nexmo'
gem 'puma'
gem 'puma_worker_killer'
gem 'mustache'
gem 'RedCloth'
gem 'rack-cors', require: 'rack/cors'
gem 'spawnling', '~>2.1'
gem 'rails-ujs'
gem 'jquery-ui-rails'
gem 'rails-jquery-autocomplete'
gem 'figaro'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capybara'
  gem 'capybara-email'
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'fabrication'
  gem 'foreman'
  gem 'forgery'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'bullet'
  gem 'rails-controller-testing'
  gem 'tzinfo-data'
end

group :development do
  gem "capistrano", "~> 3.10", require: false
  gem "capistrano-rails", "~> 1.4", require: false
  gem 'capistrano-rvm'
end

group :doc do
  gem 'sdoc', require: false
end

group :production do
  #gem 'rails_12factor'
  gem 'heroku-deflater'
  gem 'rack-cache'
  gem 'dalli'
  gem 'tunemygc'
  gem 'newrelic_rpm'
end
